id: opecha:P002933
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE20
  title: དམབནིརསགཊུ་བུཨི་ཏམུ-ཨུད་ཨེཅེ་ཀུམུན-ཨུ་བཡིདལཌུར་ནེཡིལྒུལུན་ཨབཅུ་ཡམབར་ཨུཨིལེ་ཀིགསེན་ཨནུ་ཨལིན་ཏམུཊུ་ཏོརུཀུཨྀ་ཏོབཅིལན་ཨོརུན-ཡིནྀ་ཨརཻ-ཨ་བལུ-ཨཌུར་ཇལྦརན་མནི་ཨུངསིqཨུ་ཨོརུསིབ
  volume: ''
  author: ''
