id: P002933
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE20
  title: དམབནིརསགཊུ་བུཨི་ཏམུ-ཨུད་ཨེཅེ་ཀུམུན-ཨུ་བཡིདལཌུར་ནེཡིལྒུལུན་ཨབཅུ་ཡམབར་ཨུཨིལེ་ཀིགསེན་ཨནུ་ཨལིན་ཏམུཊུ་ཏོརུཀུཨྀ་ཏོབཅིལན་ཨོརུན-ཡིནྀ་ཨརཻ-ཨ་བལུ-ཨཌུར་ཇལྦརན་མནི་ཨུངསིqཨུ་ཨོརུསིབ
  author: ''
  volumes:
    924b1d1a6bdf49669370b3573e75657b:
      image_group_id: I1KG16832
      title: ''
      volume_number: 1
      total_pages: 793
      base_file: v001.txt
