id: IC74003F2
legacy_id: P002933
ocr_import_info:
  bdrc_scan_id: W1EE20
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T00:20:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:43:16.222039+00:00'
last_modified: 2022-08-31 03:44:07.812937
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1EE20
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1EE20
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: dambanirsag-tu bui tamu-ud ece kumun-u bayidal-dur neyilgulun abcu yambar
    uile kigsen anu alin tamu-tu toruku-i tobcilan orun-yin-i arai-a balu-a-dur jalbaran
    mani ungsiqu orusiba
statistics:
  ocr_word_mean_confidence_index: 0.6342167544801286
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I1KG16832:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16832
      total_pages: 793
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16832.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6342167544801286
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
