id: IC74003F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:24:53+00:00'
last_modified: '2022-06-07T16:18:28.558319+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE20
  title: དམབནིརསགཊུ་བུཨི་ཏམུ-ཨུད་ཨེཅེ་ཀུམུན-ཨུ་བཡིདལཌུར་ནེཡིལྒུལུན་ཨབཅུ་ཡམབར་ཨུཨིལེ་ཀིགསེན་ཨནུ་ཨལིན་ཏམུཊུ་ཏོརུཀུཨྀ་ཏོབཅིལན་ཨོརུན-ཡིནྀ་ཨརཻ-ཨ་བལུ-ཨཌུར་ཇལྦརན་མནི་ཨུངསིqཨུ་ཨོརུསིབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F43B:
      image_group_id: I1KG16832
      title: ''
      total_pages: 793
      order: 1
      base_file: F43B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
